definitions:
  Controller.CommonError:
    properties:
      error:
        type: string
    type: object
  Controller.CreateUserRequest:
    properties:
      age:
        type: integer
      email:
        type: string
      name:
        type: string
    type: object
  Controller.DefaultResponse:
    properties:
      info:
        type: string
    type: object
  models.User:
    properties:
      age:
        type: integer
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact:
    email: test@test.com
    name: onlineshop api
    url: http://test.com
  title: onlineshop
paths:
  /users:
    get:
      description: getting list of all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Controller.CommonError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Controller.CommonError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Controller.CommonError'
      summary: getting users
      tags:
      - Users
    post:
      description: creating new user
      parameters:
      - description: user info
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/Controller.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/Controller.DefaultResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Controller.CommonError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Controller.CommonError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/Controller.CommonError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Controller.CommonError'
      summary: creating
      tags:
      - Users
  /users/{id}:
    delete:
      description: delete user by id
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Controller.DefaultResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Controller.CommonError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Controller.CommonError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Controller.CommonError'
      summary: deleting
      tags:
      - Users
    get:
      description: getting a user by id
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Controller.CommonError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Controller.CommonError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Controller.CommonError'
      summary: getting user
      tags:
      - Users
    put:
      description: updating user by id
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      - description: user info
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/Controller.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Controller.DefaultResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Controller.CommonError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/Controller.CommonError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/Controller.CommonError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Controller.CommonError'
      summary: updating
      tags:
      - Users
swagger: "2.0"
